### ISSUE TITLE
Why is lite version so fast? It shouldn't be.

### ISSUE THREAD

**Issue by quentin389** [quentin389/ua-speed-tests#2]
See https://github.com/browscap/browscap/issues/9

Try to get to the bottom of the issue - why is the lite version so fast when using `get_browser` even though it's just 1/2 the size of the normal version? Maybe the regexes speed doesn't scale lineary? But if that's not the case then it's most likely a bug...

**Comment by asgrim** [comment]
Now that lite version is out, how do speed differences compare?

**Comment by quentin389** [comment]
I didn't check that yet :|
